title: Services
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: hero
            field:
              type: group
              display: Hero
              fields:
                -
                  handle: header
                  field:
                    type: text
                    display: Header
                -
                  handle: description
                  field:
                    type: markdown
                    display: Description
                -
                  handle: image
                  field:
                    max_files: 1
                    container: assets
                    type: assets
                    display: Image
                -
                  handle: action
                  field:
                    type: group
                    display: Action
                    fields:
                      -
                        handle: text
                        field:
                          type: text
                          display: Text
                      -
                        handle: link
                        field:
                          type: link
                          display: Link
          -
            handle: two_cols_text
            field:
              type: group
              display: 'Two cols text'
              fields:
                -
                  handle: header
                  field:
                    type: text
                    display: Header
                -
                  handle: description
                  field:
                    type: markdown
                    display: Description
          -
            handle: quote
            field:
              type: group
              display: Quote
              fields:
                -
                  handle: text
                  field:
                    type: textarea
                    display: Text
          -
            handle: centered_cards
            field:
              type: group
              display: Cards
              fields:
                -
                  handle: header
                  field:
                    type: text
                    display: Header
                -
                  handle: description
                  field:
                    type: markdown
                    display: Description
                -
                  handle: cards
                  field:
                    type: replicator
                    display: Cards
                    sets:
                      new_set_group:
                        display: 'New Set Group'
                        sets:
                          card:
                            display: Card
                            fields:
                              -
                                handle: color
                                field:
                                  type: color
                                  display: Color
                                  width: 50
                              -
                                handle: color_end
                                field:
                                  type: color
                                  display: 'Color end'
                                  width: 50
                              -
                                handle: icon
                                field:
                                  max_files: 1
                                  container: assets
                                  type: assets
                                  display: Icon
                              -
                                handle: header
                                field:
                                  type: text
                                  display: Header
                              -
                                handle: description
                                field:
                                  type: markdown
                                  display: Description
                -
                  handle: image
                  field:
                    max_files: 1
                    container: assets
                    type: assets
                    display: Image
                    instructions: 'In case you have less that 3 cards, image will be displayed.'
          -
            handle: full_image
            field:
              type: group
              display: 'Full image'
              fields:
                -
                  handle: image
                  field:
                    max_files: 1
                    container: assets
                    type: assets
                    display: Image
          -
            handle: cta
            field:
              type: group
              display: CTA
              fields:
                -
                  handle: header
                  field:
                    type: text
                    display: Header
                -
                  handle: description
                  field:
                    type: markdown
                    display: Description
                -
                  handle: action
                  field:
                    type: group
                    display: Action
                    fields:
                      -
                        handle: text
                        field:
                          type: text
                          display: Text
                      -
                        handle: link
                        field:
                          type: link
                          display: Link
                -
                  handle: image
                  field:
                    max_files: 1
                    container: assets
                    type: assets
                    display: Image
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - pages
              max_items: 1
              listable: false
              localizable: true
          -
            handle: template
            field:
              type: template
              display: Template
  alt_seo:
    display: 'Alt SEO'
    sections:
      -
        fields:
          -
            handle: alt_seo_options
            field:
              type: section
              display: 'Alt SEO'
              instructions: 'You can use the following variables: {title}, {site_name}, {description}, or any antlers variable from on page'
          -
            handle: alt_seo_meta_title
            field:
              display: 'SEO Title'
              type: text
              character_limit: 100
              instructions: 'For an SEO-optimized page title in Google, the magic number typically hovers around 50-60 characters. While Google may stretch to show up to 70 characters, keeping your titles within that 50-60 range ensures they stay sleek and fully visible in the search results.'
              localizable: true
          -
            handle: alt_seo_meta_description
            field:
              display: 'SEO Descriptions'
              type: textarea
              character_limit: 200
              instructions: "The optimal length for an SEO-friendly meta description in Google is typically around 150-160 characters. Google may display up to 160 characters, but it's a good practice to keep your meta descriptions within this range to ensure they provide a concise and informative snippet in the search results."
              localizable: true
          -
            handle: alt_seo_canonical_url
            field:
              display: 'Canonical URL'
              type: text
              instructions: 'Canonical URLs are essential for avoiding duplicate content issues and consolidating link signals for a single page. Make sure to set a canonical URL for each page to help search engines understand which version of the page to index and rank. Leave this empty to default to the current page.'
              localizable: true
          -
            handle: alt_seo_noindex
            field:
              width: 50
              display: 'Set this page to noindex?'
              type: toggle
              localizable: true
          -
            handle: alt_seo_nofollow
            field:
              width: 50
              display: 'Set this page to nofollow?'
              type: toggle
              localizable: true
          -
            handle: alt_social_options
            field:
              type: section
              display: 'Social Options'
              instructions: 'Fields for sharing on social media and other platforms'
          -
            handle: alt_seo_social_title
            field:
              display: 'Social Title'
              type: text
              character_limit: 100
              instructions: 'When crafting titles for social media sharing, keep them short and snappy, ideally within the 60-character range. Concise titles tend to perform better on social platforms by capturing attention and encouraging clicks and shares.'
              localizable: true
          -
            handle: alt_seo_social_description
            field:
              display: 'Social Descriptions'
              type: textarea
              character_limit: 200
              instructions: 'Keep social media sharing descriptions super concise, typically around 100 characters. Shorter descriptions tend to be more shareable and effective in grabbing attention.'
              localizable: true
          -
            handle: alt_seo_social_image
            field:
              container: assets
              max_files: 1
              display: 'Social Image'
              instructions: 'For social media sharing images, go for a clear, attention-grabbing square or vertical format image. A size of around 1200x1200 or 1200x1500 pixels usually works best for various platforms.'
              type: assets
              always_save: false
              localizable: true
  alt_sitemap:
    display: 'Alt Sitemap'
    sections:
      -
        fields:
          -
            handle: sitemap_priority
            field:
              type: float
              display: 'Sitemap Priority'
              instructions: 'From 0.0 (lowest priority) to 1.0 (highest priority)'
          -
            handle: exclude_from_sitemap
            field:
              type: toggle
              display: 'Exclude from sitemap?'
